### two dimensional array


In [6]:
import numpy as np


In [8]:
sample_matrix=np.array([[50,20,1,3],[24,22,21,23],[56,76,24,7]])
sample_matrix

array([[50, 20,  1,  3],
       [24, 22, 21, 23],
       [56, 76, 24,  7]])

In [9]:
sample_matrix[1,2]

21

In [10]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [11]:
sample_matrix[2]

array([56, 76, 24,  7])

In [12]:
sample_matrix[:,(3,2)]

array([[ 3,  1],
       [23, 21],
       [ 7, 24]])

##selection technique

#SELECTION TECHNIQUE

In [15]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [16]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [17]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [18]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [19]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [20]:
np.max(sample_array)

19

In [21]:
np.min(sample_array)

1

In [22]:
np.argmax(sample_array)

18

In [23]:
np.argmin(sample_array)

0

In [24]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [25]:
np.std(sample_array)

5.477225575051661

In [26]:
np.var(sample_array)

30.0

In [27]:
np.mean(sample_array)

10.0

In [29]:
array=np.random.randn(3,4)
array

array([[ 0.45676918,  1.28316581, -0.4111191 ,  0.20435203],
       [-0.32756972,  0.17267974,  0.13233543,  0.27057094],
       [-0.00672048, -0.58674449, -1.37425703, -0.16111121]])

In [32]:
np.round(array,decimals=2)

array([[ 0.46,  1.28, -0.41,  0.2 ],
       [-0.33,  0.17,  0.13,  0.27],
       [-0.01, -0.59, -1.37, -0.16]])

In [36]:
sports=np.array(['golf','cricket','fball','cricket'])
sports


array(['golf', 'cricket', 'fball', 'cricket'], dtype='<U7')

In [35]:
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

#PANDA

# PANDA

In [38]:
import pandas as pd
import numpy as np

In [45]:
sport1=pd.Series([1,2,3,4],index=['cricket','football','golf','bball'])
sport1

cricket     1
football    2
golf        3
bball       4
dtype: int64

In [46]:
sport1['football']

2

In [47]:
sport2=pd.Series([11,2,3,4],index=['cricket','football','bball','golf'])
sport2                 

cricket     11
football     2
bball        3
golf         4
dtype: int64

In [48]:
sport1+sport2

bball        7
cricket     12
football     4
golf         7
dtype: int64

In [49]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H '.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.092448  0.913090  0.166320  0.855600  0.968518
B  0.230390  0.382808  0.931282  0.981165  0.463775
C  0.022001  0.084436  0.889445  0.656846  0.309484
D  0.429704  0.983017  0.184688  0.979411  0.599283
E  0.076814  0.841808  0.080391  0.276825  0.953308
F  0.448009  0.310957  0.055453  0.542500  0.569815
G  0.629908  0.588174  0.054512  0.629201  0.555873
H  0.390349  0.685989  0.509907  0.561991  0.252120

In [50]:
df1['score1']

A    0.092448
B    0.230390
C    0.022001
D    0.429704
E    0.076814
F    0.448009
G    0.629908
H    0.390349
Name: score1, dtype: float64

In [55]:
df1['score1']+df1['score2']
df1

score1    score2    score3    score4    score5    score6
A  0.092448  0.913090  0.166320  0.855600  0.968518  1.005538
B  0.230390  0.382808  0.931282  0.981165  0.463775  0.613198
C  0.022001  0.084436  0.889445  0.656846  0.309484  0.106436
D  0.429704  0.983017  0.184688  0.979411  0.599283  1.412721
E  0.076814  0.841808  0.080391  0.276825  0.953308  0.918622
F  0.448009  0.310957  0.055453  0.542500  0.569815  0.758966
G  0.629908  0.588174  0.054512  0.629201  0.555873  1.218082
H  0.390349  0.685989  0.509907  0.561991  0.252120  1.076339

In [53]:
df1["score6"]=df1["score1"]+df1["score2"]
df1

score1    score2    score3    score4    score5    score6
A  0.092448  0.913090  0.166320  0.855600  0.968518  1.005538
B  0.230390  0.382808  0.931282  0.981165  0.463775  0.613198
C  0.022001  0.084436  0.889445  0.656846  0.309484  0.106436
D  0.429704  0.983017  0.184688  0.979411  0.599283  1.412721
E  0.076814  0.841808  0.080391  0.276825  0.953308  0.918622
F  0.448009  0.310957  0.055453  0.542500  0.569815  0.758966
G  0.629908  0.588174  0.054512  0.629201  0.555873  1.218082
H  0.390349  0.685989  0.509907  0.561991  0.252120  1.076339

In [56]:
df2={'id':['101','757','464','538','663'],'NAME':['aditi','atin','trujal','brinjal','snehu'],'PROFIT':[23,5,64,53,24]}
df=pd.DataFrame(df2)
df

id     NAME  PROFIT
0  101    aditi      23
1  757     atin       5
2  464   trujal      64
3  538  brinjal      53
4  663    snehu      24

In [57]:
df["id"]

0    101
1    757
2    464
3    538
4    663
Name: id, dtype: object

In [59]:
df=df.drop["id",axis=1]
df

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (315106153.py, line 1)

In [60]:
df.drop(3)

id    NAME  PROFIT
0  101   aditi      23
1  757    atin       5
2  464  trujal      64
4  663   snehu      24

In [ ]:
# HOW TO IMPORT DATABASE USING PANDA