### NUMPY

In [1]:
import numpy as np


In [3]:
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

## numpy means play with arrays

In [4]:
arr=np.array([1,2,3])

In [5]:
arr

array([1, 2, 3])

In [6]:
list_of_lists=[[1,2,3],[4,5,6],[6,7,8]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
np.arrange(1,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

AttributeError: module 'numpy' has no attribute 'twos'

In [18]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [19]:
np.linespace(0,2,5)

AttributeError: module 'numpy' has no attribute 'linespace'

In [20]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
np.linspace(1,20,8)

array([ 1.        ,  3.71428571,  6.42857143,  9.14285714, 11.85714286,
       14.57142857, 17.28571429, 20.        ])

In [22]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [23]:
np.random.rand(3,5)

array([[0.30991812, 0.06136452, 0.70119128, 0.71381264, 0.09150927],
       [0.06848945, 0.14121077, 0.55680609, 0.05316665, 0.65782306],
       [0.28491084, 0.9289684 , 0.85993395, 0.89098962, 0.34941036]])

In [26]:
arr=np.random.randn(2,4)
arr

array([[ 0.2071075 ,  0.16166006, -0.83784901, -0.13069899],
       [ 1.59633631, -0.25390855, -1.10256598, -0.33694904]])

In [28]:
np.random.randint(2,100)

77

In [30]:
np.random.randint(20,56,100)

array([51, 52, 45, 37, 53, 26, 27, 42, 40, 42, 51, 38, 21, 50, 51, 52, 32,
       29, 43, 35, 32, 33, 49, 26, 36, 39, 29, 37, 24, 34, 44, 47, 31, 45,
       42, 36, 24, 28, 31, 47, 22, 43, 42, 52, 24, 51, 48, 45, 55, 33, 22,
       41, 31, 30, 29, 36, 46, 53, 41, 20, 44, 48, 32, 47, 22, 27, 33, 29,
       38, 44, 32, 20, 49, 26, 55, 22, 39, 35, 53, 37, 23, 23, 22, 41, 29,
       47, 22, 41, 50, 22, 37, 39, 25, 41, 40, 22, 49, 34, 24, 23])

In [32]:
simple_array=np.arange(30)
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
rand_array=np.random.randint(0,10,50)
rand_array

array([4, 4, 0, 9, 2, 9, 7, 2, 9, 5, 6, 9, 8, 0, 3, 0, 3, 0, 5, 4, 0, 4,
       2, 4, 2, 0, 9, 8, 8, 3, 7, 5, 8, 9, 3, 6, 3, 0, 7, 3, 4, 4, 0, 7,
       6, 2, 2, 1, 7, 8])

In [34]:
simple_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
simple_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)